# Generated by Django 6.0.6 on 2026-06-14 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technique'), ('full', 'Complet')], max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('qa_pairs', models.JSONField(default=list)),
                ('emotion_log', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('global_score', models.FloatField(default=0.0)),
                ('verbal_score', models.FloatField(default=0.0)),
                ('stress_score', models.FloatField(default=0.0)),
                ('body_language_score', models.FloatField(default=0.0)),
                ('text_quality_score', models.FloatField(default=0.0)),
                ('feedback', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('interview_type', models.CharField(max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('current_question_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_data', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
